name: project
description: A new Flutter project

environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  parse_server_sdk: ^3.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Optional: For linting your Flutter code

flutter:
  uses-material-design: true
  assets:
    - assets/



